services:
  # Mock Service Dependency
  wiremock-gateway:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Quality Platform Test Runner
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n26-quality-runner
    environment:
      # Docker Internal DNS Name targeting the WireMock container
      - TARGET_BASE_URL=http://wiremock-gateway:8080
    volumes:
      - ./target/surefire-reports:/home/qa/app/target/surefire-reports
    depends_on:
      wiremock-gateway:
        condition: service_healthy